name: Build Android App

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK and accept licenses
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip tools.zip
        mv cmdline-tools latest

        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses
        sdkmanager "platforms;android-31" "build-tools;31.0.0"

    - name: Build APK and AAB
      env:
        ANDROIDSDK: $HOME/android-sdk
        ANDROID_NDK_HOME: $HOME/.buildozer/android/platform/android-ndk-r25b
        PATH: /usr/bin:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
      run: |
        buildozer android debug
        buildozer android release

    - name: Upload APK and AAB
      uses: actions/upload-artifact@v4
      with:
        name: eventplanner-builds
        path: |
          bin/*.apk
          bin/*.aab
