name: Build Android App

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies and Android SDK
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk zip unzip git wget
        pip install buildozer cython

        # Install Android SDK command line tools
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
        unzip tools.zip
        mv cmdline-tools latest

        # Set environment and accept licenses
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-31" "build-tools;31.0.0"

    - name: Build APK and AAB
      env:
        ANDROIDSDK: $HOME/android-sdk
        ANDROID_NDK_HOME: $HOME/.buildozer/android/platform/android-ndk-r25b
        PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$PATH
      run: |
        sudo apt install -y git
        buildozer android debug
        buildozer android release

    - name: Upload APK and AAB
      uses: actions/upload-artifact@v4
      with:
        name: eventplanner-builds
        path: |
          bin/*.apk
          bin/*.aab

# Optional: Auto-create a GitHub release (Uncomment to enable)
#    - name: Create GitHub Release
#      uses: softprops/action-gh-release@v2
#      with:
#        tag_name: "v1.0.${{ github.run_number }}"
#        name: "Event Planner App Build ${{ github.run_number }}"
#        files: |
#          bin/*.apk
#          bin/*.aab
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
